[package]
name = "stack-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8"
regex = "0.1"
sys-info = "0.7.0"
clap = "3.0"
percent-encoding = "2.1.0"
